language: rust

# Need to cache the whole `.cargo` directory to keep .crates.toml for
# cargo-update to work
#
cache:
  directories:
    - /home/travis/.cargo

# But don't cache the cargo registry
# and remove wasm-pack binary to avoid the installer asking confirmation for overwriting it.
#
before_cache:
  - rm -rf /home/travis/.cargo/git
  - rm -rf /home/travis/.cargo/registry
  - rm -rf /home/travis/.cargo/bin/cargo-tarpaulin


branches:
  only:
    - master
    - dev

jobs:

  include:

    - name: linux stable rust
      os  : linux
      rust: stable

      script:
        - bash ci/test.bash


    - name: linux nightly rust
      os  : linux
      dist: bionic # required for tarpaulin binary distribution to work.
      rust: nightly

      addons:
        apt:
          packages:
            - libssl-dev # for cargo-tarpaulin


      script:
        - bash ci/test.bash
        - bash ci/doc.bash
        - bash ci/coverage.bash


    - name: osx stable rust
      os  : osx
      rust: stable

      script:
        - bash ci/test.bash


    - name: windows stable rust
      os  : windows
      rust: stable

      script:
        - bash ci/test.bash





